"""
Create Card Template Tables.

Revision ID: becfc3d9a041
Revises:
Create Date: 2025-11-10 18:32:15.989324
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "becfc3d9a041"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_templates",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("image_file_name", sa.String(), nullable=False),
        sa.Column("likes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "card_template_categories",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.Enum("BIRTHDAY", "SYMPATHY", "GET_WELL_SOON", "CONGRATULATIONS", name="cardtemplatecategory"), nullable=False),
        sa.Column("card_template_uuid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["card_template_uuid"], ["card_templates.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("card_template_uuid", "name", name="unique_card_template_category"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_template_categories")
    op.drop_table("card_templates")
    # ### end Alembic commands ###
